name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to GitHub Docker registry
      run: echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u t0nyz0 --password-stdin

    - name: Build Docker image
      run: docker build . -t ghcr.io/t0nyz0/bambuboard-h2d:latest

    - name: Push Docker image to GitHub Packages
      run: docker push ghcr.io/t0nyz0/bambuboard-h2d:latest
